### PR TITLE
Fix wrong axis alignment

### PR DESCRIPTION
**Pull request by maisonsmd**
magnetic sensor has Z axis inverted

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I can confirm this is a problem, passing the inverted value of `mz` solves it.

**Comment by kriswiner** [comment]
Glad this works for you.

Which direction of the board (or Ax typically) points toward true north is
up to the user and is arbitrary. Once this is chosen, the sensor data needs
to be fed into the fusion algorithms conforming to either NED or ENU RHS
convention. So this will depend on the sensor suite. But yes, for the
MPU9250, if DOWN is Az then DOWN has to be -Mz.

**Comment by robertoostenveld** [comment]
hmm, I am currently not totally sure about my prior conformation. I noticed that - after making the change - the AHRS worked fine (from the top of my head it was NWU, which is a right-handed system just like NED and ENU), but that convergence was very slow. I now wonder whether that might be due to a remaining axis misalignment.

The MPU9250 is according to figure 4 and 5 in http://www.invensense.com/wp-content/uploads/2015/02/PS-MPU-9250A-01-v1.1.pdf

Screen Shot 2019-05-13 at 14 36 12

which for the break-out-board version from e.g. [Ebay](https://www.ebay.com/itm/SPI-IIC-MPU-9250-9-Axis-Attitude-Gyro-Accelerator-Magnetometer-Sensor-Module-/281866691541?_ul=CR) means 

Screen Shot 2019-05-13 at 14 36 50
 
So keeping (x,y,z) for accelerometer and gyro as they are, and for the magnetometer taking (y,x,-z) seems correct. It also maintains the magnetometer axes in a right-handed coordinate system, whereas the original code changes from a right-handed to a left-handed coordinate system.

I will check it further and report back.

**Comment by maisonsmd** [comment]
Hi @robertoostenveld !
I'm currently using the same board as yours.
Did you calib the accel and magetic sensor? 
This is my magetic raw data without calibration, as you can see there a huge bias in each axis:
image
And after calibrating (scale & bias):
image
After calibrating accel and magnetic, I got the right angle.
So I'm pretty sure that inverting magnetic Z resolves problem.

The slow convergence is because Kp, Beta is not suitable for your sensor, I had to hand-changing them to find the best fit.
I also had to multiply gyroscope values to some constant (maybe its sensivity is not so correct).
image

After all that, I've got fast response, correct value.
The result is pretty same as this:
https://youtu.be/BXsGWoOMtmU

Hope this help!

**Comment by maisonsmd** [comment]
@robertoostenveld Thinking about slow convergence, try setting gyro scale to highest (2000 deg/sec), because when you set it low (eg: 250deg/sec), it cannot measure fast rotation.

**Comment by kriswiner** [comment]
Of course, this is all nonsense. The slow convergence is due to one of two
things. Either your MCU isn't running fast enough to maintain 5 - 10 x
fusion rate versus gyro sample rate or you are not feeding the sensor data
into the fusion filter properly (i.e., NED or ENU). Convergence has nothing
to do with beta. Or the gyro rate, unless you are using this on an
automobile wheel or something...

**Comment by maisonsmd** [comment]
@kriswiner Update: I had to multiply gyro because I didn't calculate the resolution properly. Now I checked and it doesn't need to multiply anymore.
In fact, I don't need to change any factor (kp, beta) above and it reponses fast!

**Comment by robertoostenveld** [comment]
Just for reference, this pull request relates to issue #368 and pull request #369 is a duplicate of this one.

**Comment by robertoostenveld** [comment]
I have tested some variants of the sketch more. 

If I change in my code the line that corresponds to [this](https://github.com/kriswiner/MPU9250/blob/72038b040bef3cf072612cd8a8ee8f26e3c87158/MPU9250BasicAHRS.ino#L433)

    MahonyQuaternionUpdate(ax, ay, az, gx*PI/180.0f, gy*PI/180.0f, gz*PI/180.0f, my, mx, mz);

into 

    MahonyQuaternionUpdate(ax, ay, az, gx*PI/180.0f, gy*PI/180.0f, gz*PI/180.0f, my, mx, -mz); 

then the yaw, roll and pitch behave as I would expect them. Also they converge smoothly. The problematic convergence that I reported at the start of [this comment](https://github.com/kriswiner/MPU9250/pull/370#issuecomment-491806904) was not a problem any more when I reverted to the default `GScale`, `Ascale` and `Mmode` values. So in summary, in my previous experimenting, I changed the scales and the minus-mz in one go, solving one, but introducing an unrelated issue. The suggested `-mz` still seems a good idea to me.

**Comment by kriswiner** [comment]
This is not arbitrary nor subject to trial and error. The sensor data need
to be sent to the fusion function in NED or ENU (consistent right-handed
coordinate system) order. The choice of which axis is to be North is
arbitrary. But once the user makes this choice, the sensor axes determine
which axes point North, East, and Down.

So having Az and Mz as third inputs to the accel and mag sensor data,
respectively, cannot possibly be right for the MPU9250 since these are
oriented opposite to each other in the sensors. You need to check whether
the other sensor data are fed in properly.

**Comment by robertoostenveld** [comment]
with *testing sketches* I mean checking with some additional serial console output that the orientations and signs of values for each of the nine axes is consistent with those specified in the invensense data sheet, prior to feeding them into the sensor fusion algorithm. I confirmed that they are consistent. 

And it is indeed as you describe, the magnetometer values should be represented in a right-hand coordinate system which is consistent with that of the accelerometer and gyroscope.

The code in [this line](https://github.com/kriswiner/MPU9250/blob/72038b040bef3cf072612cd8a8ee8f26e3c87158/MPU9250BasicAHRS.ino#L433) feeds the magnetometer values in the order (my, mx, mz) to the [MahonyQuaternionUpdate](https://github.com/kriswiner/MPU9250/blob/72038b040bef3cf072612cd8a8ee8f26e3c87158/quaternionFilters.ino#L104) function. Flipping mx and my in the input values, but keeping mz as it is, results in a left handed coordinate system. The proposed input arguments (my,  mx, -mz) are in a right handed system and aligned with (ax, ay, az) and (gx, gy, gz). 

Do with it what you wish.

**Comment by kriswiner** [comment]
If you've checked this for NED consistency then it should work well and not
display large latency nor odd cross axis effects as is often reported when
this RHS requirement is not met. As long as you have also calibrated the
sensors well you should be able to achieve absolute orientation accuracy of
<4 degrees rms in heading and 1 degree rms in pitch and roll using these
relatively simple fusion methods.

**Comment by maisonsmd** [comment]
Closing due to no update for the past 5 years.

**Pull request closed without merging**
